# Generated by Django 5.0.6 on 2024-05-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('editora', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('idioma', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('formato', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='home.usuario')),
            ],
        ),
    ]
